name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "16.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b58d793b19f89c09e918f6ec53e7b0ed7c5091bd1df7500c00a8d1a95d6e3d3e"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
