name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d0fa3072aa999b8cf502ca97f5daf0ce73b761d0f3beae1be3c0fbed60f92ca"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
