name = "Nova MTR"
author = "AwesomeKalin55, Quanti, Curt"
version = "29.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3c2fd74328bce854479b45e43b6711754a95a586e41f3118e4f54ea22dae34"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
